---
- name: This Playbook is to install apache2 and httpd
  hosts: all
  become: true
  vars:
    port: 8082
  tasks:
  - name: install package
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"
    notify: start apache service

  - name: install apache2 service
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    notify: start apache2 service
 
  - name: Ensure the default Apache port is {{ port }}
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen '
      insertafter: '^#Listen '
      line: Listen {{ port }}
    when: ansible_os_family == "RedHat"
    notify: restart apache service 

  - name: Ensure the default Apache port is {{ port }} on ubuntu
    lineinfile: 
      path: /etc/apache2/ports.conf
      regexp: '^Listen '
      insertafter: '# /etc/apache2/sites-enabled/000-default.conf'
      line: Listen {{ port }}
    when: ansible_os_family == "Debian"
    notify: restart apache2 service

  handlers:
  - name: start apache service
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"

  - name: start apache2 service
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"

  - name: restart apache service
    service:
      name: httpd
      state: restarted
    when: ansible_os_family == "RedHat"

  - name: restart apache2 service
    service:
      name: apache2
      state: restarted
    when: ansible_os_family == "Debian"
