---
- name: This Playbook is to uninstall apache2
  hosts: dbservers
  become: true
  tasks:
  - name: stop apache2 service
    service:
      name: apache2
      state: stopped
  - name: uninstall apache2
    apt:
      name: apache2
      state: absent
